name: Build
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: './go.mod'
    - name: Go Format
      run: gofmt -s -w . && git diff --exit-code
    - name: Go Vet
      run: go vet ./...
    - name: Go Tidy
      run: go mod tidy && git diff --exit-code
    - name: Go Mod
      run: go mod download
    - name: Go Mod Verify
      run: go mod verify
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v -count=1 -shuffle=on ./...
